import { NextResponse } from "next/server";
import { readSession } from "@/lib/auth";
import { transaction } from "@/lib/db";

function normalizeRun(value) {
  return String(value || "").replace(/[^0-9kK]/g, "").toLowerCase();
}

function asNullableText(value) {
  const text = String(value || "").trim();
  return text || null;
}

function asNullableInt(value) {
  if (value === null || value === undefined || value === "") return null;
  const number = Number(value);
  return Number.isFinite(number) ? number : null;
}

function asTimestamp(value) {
  const text = String(value || "").trim();
  if (!text) return null;
  const date = new Date(text);
  return Number.isNaN(date.getTime()) ? null : date;
}

function normalizeRepairs(order = {}) {
  const repairRows = Array.isArray(order.reparaciones) ? order.reparaciones : [];
  const repairs = repairRows
    .map((repair) => ({
      reparacion_id: asNullableInt(repair.reparacion_id),
      inventario_item_id: asNullableInt(repair.inventario_item_id),
      precio_unitario: asNullableInt(repair.precio_unitario),
    }))
    .filter((repair) => repair.reparacion_id);

  if (!repairs.length && asNullableInt(order.reparacion_id)) {
    repairs.push({
      reparacion_id: asNullableInt(order.reparacion_id),
      inventario_item_id: asNullableInt(order.inventario_item_id),
      precio_unitario: asNullableInt(order.precio_unitario),
    });
  }

  return repairs;
}

function validate(body) {
  const client = body.client || {};
  const order = body.order || {};
  const repairs = normalizeRepairs(order);

  if (!normalizeRun(client.run)) return "Debe ingresar un RUN valido.";
  if (!asNullableText(client.nombre)) return "Debe ingresar el nombre del cliente.";
  if (!asNullableText(client.fono)) return "Debe ingresar el contacto del cliente.";
  if (!asNullableInt(order.id_equipo)) return "Debe seleccionar el equipo.";
  if (!asNullableInt(order.id_dispositivo)) return "Debe seleccionar el modelo.";
  if (!repairs.length) return "Debe seleccionar al menos una reparacion.";
  if (!asNullableInt(order.estado_dispositivo)) return "Debe seleccionar el estado del equipo.";

  return null;
}

export async function POST(request) {
  const session = await readSession();
  if (!session) {
    return NextResponse.json({ message: "No autorizado." }, { status: 401 });
  }

  const body = await request.json().catch(() => ({}));
  const validationMessage = validate(body);
  if (validationMessage) {
    return NextResponse.json({ message: validationMessage }, { status: 400 });
  }

  const clientPayload = body.client || {};
  const orderPayload = body.order || {};
  const repairsPayload = normalizeRepairs(orderPayload);
  const answersPayload = Array.isArray(body.answers) ? body.answers : [];
  const normalizedRun = normalizeRun(clientPayload.run);

  try {
    const result = await transaction(async (db) => {
      await db.query("alter table ordenes add column if not exists reparacion_id integer references repuestos(id)");
      await db.query(`
        create table if not exists orden_repuestos (
          id integer generated by default as identity primary key,
          orden_id integer references ordenes(id) on delete cascade,
          inventario_item_id integer references inventario_items(id),
          repuesto_id integer references repuestos(id),
          cantidad integer not null default 1,
          costo_unitario integer default 0,
          precio_unitario integer default 0,
          total_costo integer default 0,
          total_venta integer default 0,
          responsable text,
          created_at timestamptz default now()
        )
      `);
      await db.query("alter table orden_repuestos add column if not exists repuesto_id integer references repuestos(id)");
      await db.query("alter table inventario_items add column if not exists ultimo_precio_venta integer");
      await db.query("alter table inventario_items add column if not exists ultimo_precio_fecha timestamptz");
      await db.query("alter table inventario_items add column if not exists ultima_orden_id integer");

      const repairEntries = [];
      for (const repair of repairsPayload) {
        let selectedItem = null;
        if (!repair.inventario_item_id) {
          repairEntries.push({ repair, selectedItem });
          continue;
        }
        const itemResult = await db.query(
          `
            select *
            from inventario_items
            where id = $1
              and area = 'taller'
              and estado = 1
              and dispositivo_id = $2
              and repuesto_id = $3
            limit 1
          `,
          [repair.inventario_item_id, asNullableInt(orderPayload.id_dispositivo), repair.reparacion_id]
        );
        selectedItem = itemResult.rows[0] || null;
        if (!selectedItem) throw new Error("Un tipo de reparacion seleccionado no corresponde al modelo.");
        repairEntries.push({ repair, selectedItem });
      }

      for (const entry of repairEntries) {
        const item = entry.selectedItem;
        entry.unitCost = Number(item?.valor_original || 0);
        entry.unitPrice =
          entry.repair.precio_unitario != null
            ? entry.repair.precio_unitario
            : Number(item?.ultimo_precio_venta ?? item?.valor_venta ?? 0);
      }

      const quoteTotal = repairEntries.reduce((sum, entry) => sum + Number(entry.unitPrice || 0), 0);
      const quoteSubtotal = quoteTotal > 0 ? Math.round(quoteTotal / 1.19) : 0;
      const quoteIva = quoteTotal - quoteSubtotal;

      const existingClient = await db.query(
        `
          select id
          from clientes
          where lower(regexp_replace(coalesce(run, ''), '[^0-9kK]', '', 'g')) = $1
          order by id asc
          limit 1
        `,
        [normalizedRun]
      );

      let clientId = existingClient.rows[0]?.id;

      if (clientId) {
        await db.query(
          `
            update clientes
            set nombre = $1, mail = $2, fono = $3, run = $4, estado = coalesce(estado, 1)
            where id = $5
          `,
          [
            asNullableText(clientPayload.nombre),
            asNullableText(clientPayload.mail),
            asNullableText(clientPayload.fono),
            asNullableText(clientPayload.run),
            clientId,
          ]
        );
      } else {
        const insertedClient = await db.query(
          `
            insert into clientes (nombre, run, mail, fono, estado)
            values ($1, $2, $3, $4, 1)
            returning id
          `,
          [
            asNullableText(clientPayload.nombre),
            asNullableText(clientPayload.run),
            asNullableText(clientPayload.mail),
            asNullableText(clientPayload.fono),
          ]
        );
        clientId = insertedClient.rows[0].id;
      }

      const insertedOrder = await db.query(
        `
          insert into ordenes (
            fecha_entrega,
            tecnico,
            cliente_id,
            imei,
            codigo,
            id_equipo,
            id_dispositivo,
            estado_dispositivo,
            reparacion_id,
            observacion,
            estado,
            total_recepcion,
            subtotal,
            iva,
            descuento,
            total,
            created_at
          )
          values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 1, $11, $12, $13, 0, $14, $15)
          returning id
        `,
        [
          asTimestamp(orderPayload.fecha_entrega),
          asNullableText(orderPayload.tecnico) || session.name || session.email,
          clientId,
          asNullableText(orderPayload.imei),
          asNullableText(orderPayload.codigo),
          asNullableInt(orderPayload.id_equipo),
          asNullableInt(orderPayload.id_dispositivo),
          asNullableInt(orderPayload.estado_dispositivo),
          repairsPayload[0]?.reparacion_id || null,
          asNullableText(orderPayload.observacion),
          asNullableInt(orderPayload.total_recepcion) || 0,
          quoteSubtotal,
          quoteIva,
          quoteTotal,
          asTimestamp(orderPayload.created_at) || new Date(),
        ]
      );

      const orderId = insertedOrder.rows[0].id;
      const answers = answersPayload
        .map((answer) => ({
          pregunta_id: asNullableInt(answer.pregunta_id),
          respuesta: asNullableText(answer.respuesta),
          check_resp: Boolean(answer.check_resp),
        }))
        .filter((answer) => answer.pregunta_id);

      for (const answer of answers) {
        await db.query(
          `
            insert into respuestas (pregunta_id, respuesta, orden_id, check_resp)
            values ($1, $2, $3, $4)
          `,
          [answer.pregunta_id, answer.respuesta, orderId, answer.check_resp]
        );
      }

      for (const entry of repairEntries) {
        const selectedItem = entry.selectedItem;
        await db.query(
          `
            insert into orden_repuestos (
              orden_id, inventario_item_id, repuesto_id, cantidad, costo_unitario, precio_unitario,
              total_costo, total_venta, responsable
            )
            values ($1, $2, $3, 1, $4, $5, $4, $5, $6)
          `,
          [
            orderId,
            selectedItem?.id || null,
            entry.repair.reparacion_id,
            entry.unitCost,
            entry.unitPrice,
            session.name || session.email,
          ]
        );

        // Guardar el ultimo valor cobrado en el repuesto del inventario.
        if (selectedItem?.id && entry.unitPrice > 0) {
          await db.query(
            `
              update inventario_items
              set ultimo_precio_venta = $1, ultimo_precio_fecha = now(), ultima_orden_id = $2, updated_at = now()
              where id = $3
            `,
            [entry.unitPrice, orderId, selectedItem.id]
          );
        }
      }

      return { orderId, clientId };
    });

    return NextResponse.json({ id: result.orderId, client_id: result.clientId }, { status: 201 });
  } catch (error) {
    console.error("create order failed", error);
    return NextResponse.json({ message: error.message || "No se pudo guardar la orden." }, { status: 500 });
  }
}
