import { query, transaction } from "@/lib/db";

export const INVENTORY_AREAS = new Set(["productos", "taller"]);

export function normalizeArea(area) {
  return INVENTORY_AREAS.has(area) ? area : "productos";
}

export function makeBarcode(area = "productos") {
  const prefix = normalizeArea(area) === "taller" ? "MTT" : "MTP";
  const time = Date.now().toString().slice(-8);
  const random = Math.floor(Math.random() * 1000).toString().padStart(3, "0");
  return `${prefix}${time}${random}`;
}

let schemaReady;

async function ensureInventorySchema() {
  if (!schemaReady) {
    schemaReady = query(`
      create table if not exists repuestos (
        id integer generated by default as identity primary key,
        nombre text not null,
        estado integer default 1
      )
    `)
      .then(() =>
        query(`
          alter table inventario_items
          add column if not exists dispositivo_id integer references dispositivos(id)
        `)
      )
      .then(() =>
        query(`
          alter table inventario_items
          add column if not exists repuesto_id integer references repuestos(id)
        `)
      )
      .then(() =>
        query("alter table inventario_items add column if not exists proveedor text")
      )
      .then(() =>
        query("alter table inventario_items add column if not exists ultimo_precio_venta integer")
      )
      .then(() =>
        query("alter table inventario_items add column if not exists ultimo_precio_fecha timestamptz")
      )
      .then(() =>
        query("alter table inventario_items add column if not exists ultima_orden_id integer")
      )
      .then(() =>
        query("alter table inventario_items add column if not exists es_general boolean default false")
      )
      .then(() =>
        query("create index if not exists inventario_items_dispositivo_id_idx on inventario_items(dispositivo_id)")
      )
      .then(() => query("create index if not exists inventario_items_repuesto_id_idx on inventario_items(repuesto_id)"))
      // Migracion: los antiguos "servicios" (diagnostico, reparacion placa logica, etc.)
      // pasan a ser repuestos de taller GENERALES (sin dispositivo => validos para todos
      // los equipos). Conservan su precio. Idempotente: no reinserta si ya existe un
      // item general con el mismo nombre. Si falla (p.ej. no hay tabla servicios) se ignora.
      .then(() =>
        query(`
          insert into inventario_items (
            area, producto, valor_original, descuento, valor_venta, cantidad,
            stock_minimo, estado, dispositivo_id, es_general, codigo_barra
          )
          select
            'taller', btrim(s.nombre), coalesce(s.costo, 0), 0, coalesce(s.precio, 0), 0,
            0, 1, null, true, 'MTG' || s.id
          from servicios s
          where coalesce(s.estado, 1) = 1
            and btrim(coalesce(s.nombre, '')) <> ''
            and not exists (
              select 1 from inventario_items ii
              where ii.es_general = true
                and lower(btrim(ii.producto)) = lower(btrim(s.nombre))
            )
        `).catch((error) => {
          console.error("service->general migration skipped", error.message);
        })
      );
  }
  return schemaReady;
}

function asSearch(search) {
  return String(search || "").trim();
}

function asOptionalId(value) {
  const number = Number(value);
  return Number.isInteger(number) && number > 0 ? number : null;
}

function asOptionalEstado(value) {
  if (value === 0 || value === 1) return value;
  if (value === "0" || value === "1") return Number(value);
  return null;
}

export async function getInventoryItems({
  area = "productos",
  search = "",
  barcode = "",
  equipoId = null,
  dispositivoId = null,
  repuestoId = null,
  proveedor = "",
  estado = null,
  page = 1,
  pageSize = 50,
  paginate = false,
} = {}) {
  await ensureInventorySchema();
  const normalizedArea = normalizeArea(area);
  const params = [normalizedArea];
  const where = ["ii.area = $1"];
  const cleanSearch = asSearch(search);
  const cleanBarcode = asSearch(barcode);
  const cleanEquipoId = asOptionalId(equipoId);
  const cleanDispositivoId = asOptionalId(dispositivoId);
  const cleanRepuestoId = asOptionalId(repuestoId);
  const cleanProveedor = asSearch(proveedor);
  const cleanEstado = asOptionalEstado(estado);

  if (cleanBarcode) {
    params.push(cleanBarcode);
    where.push(`ii.codigo_barra = $${params.length}`);
  }

  if (cleanSearch) {
    params.push(`%${cleanSearch}%`);
    where.push(`(
      ii.producto ilike $${params.length}
      or ii.marca ilike $${params.length}
      or ii.codigo_barra ilike $${params.length}
      or ii.ubicacion ilike $${params.length}
      or ii.proveedor ilike $${params.length}
      or d.nombre ilike $${params.length}
      or e.nombre ilike $${params.length}
      or r.nombre ilike $${params.length}
    )`);
  }

  if (cleanEquipoId) {
    params.push(cleanEquipoId);
    where.push(`e.id = $${params.length}`);
  }

  if (cleanDispositivoId) {
    params.push(cleanDispositivoId);
    where.push(`(ii.dispositivo_id = $${params.length} or ii.dispositivo_id is null)`);
  }

  if (cleanRepuestoId) {
    params.push(cleanRepuestoId);
    where.push(`ii.repuesto_id = $${params.length}`);
  }

  if (cleanProveedor) {
    params.push(cleanProveedor);
    where.push(`ii.proveedor = $${params.length}`);
  }

  if (cleanEstado !== null) {
    params.push(cleanEstado);
    where.push(`ii.estado = $${params.length}`);
  }

  const safePageSize = paginate ? Math.min(Math.max(Number(pageSize) || 50, 1), 200) : 500;
  const safePage = paginate ? Math.max(Number(page) || 1, 1) : 1;
  const offset = (safePage - 1) * safePageSize;
  const totalSelect = paginate ? "count(*) over()::int as total_count," : "";

  params.push(safePageSize);
  const limitParam = params.length;
  params.push(offset);
  const offsetParam = params.length;

  const result = await query(
    `
      select
        ${totalSelect}
        ii.id,
        ii.area,
        ii.marca,
        ii.producto,
        ii.codigo_barra,
        ii.valor_original,
        ii.descuento,
        ii.valor_venta,
        ii.cantidad,
        ii.stock_minimo,
        ii.ubicacion,
        ii.proveedor,
        ii.notas,
        ii.estado,
        ii.dispositivo_id,
        ii.repuesto_id,
        ii.es_general,
        ii.ultimo_precio_venta,
        ii.ultimo_precio_fecha,
        ii.ultima_orden_id,
        e.id as equipo_id,
        d.nombre as dispositivo_nombre,
        e.nombre as equipo_nombre,
        r.nombre as repuesto_nombre,
        ii.created_at,
        ii.updated_at
      from inventario_items ii
      left join dispositivos d on d.id = ii.dispositivo_id
      left join equipos e on e.id = d.modelo
      left join repuestos r on r.id = ii.repuesto_id
      where ${where.join(" and ")}
      order by ii.estado desc, ii.producto asc, ii.id asc
      limit $${limitParam} offset $${offsetParam}
    `,
    params
  );

  if (paginate) {
    const total = result.rows[0]?.total_count ?? 0;
    const items = result.rows.map(({ total_count, ...row }) => row);
    return { items, total, page: safePage, pageSize: safePageSize };
  }

  return result.rows;
}

export async function getInventoryStats(area = "productos") {
  await ensureInventorySchema();
  const result = await query(
    `
      select
        count(*)::int as items,
        coalesce(sum(cantidad), 0)::int as unidades,
        coalesce(sum(cantidad * valor_venta), 0)::int as valorizado,
        count(*) filter (where estado = 1 and cantidad <= stock_minimo)::int as bajo_stock
      from inventario_items
      where area = $1
    `,
    [normalizeArea(area)]
  );
  return result.rows[0];
}

export async function getInventoryProviders(area = "taller") {
  await ensureInventorySchema();
  const result = await query(
    `
      select distinct proveedor
      from inventario_items
      where area = $1
        and proveedor is not null
        and btrim(proveedor) <> ''
      order by proveedor asc
    `,
    [normalizeArea(area)]
  );
  return result.rows.map((row) => row.proveedor);
}

export async function getInventoryItem(id) {
  await ensureInventorySchema();
  const result = await query(
    `
      select
        ii.*,
        e.id as equipo_id,
        d.nombre as dispositivo_nombre,
        e.nombre as equipo_nombre,
        r.nombre as repuesto_nombre
      from inventario_items ii
      left join dispositivos d on d.id = ii.dispositivo_id
      left join equipos e on e.id = d.modelo
      left join repuestos r on r.id = ii.repuesto_id
      where ii.id = $1
    `,
    [id]
  );
  return result.rows[0] || null;
}

export async function createInventoryItem(payload) {
  await ensureInventorySchema();
  const barcode = payload.codigo_barra || makeBarcode(payload.area);
  const result = await query(
    `
      insert into inventario_items (
        area,
        marca,
        producto,
        codigo_barra,
        valor_original,
        descuento,
        valor_venta,
        cantidad,
        stock_minimo,
        ubicacion,
        proveedor,
        notas,
        estado,
        dispositivo_id,
        repuesto_id
      )
      values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
      returning *
    `,
    [
      normalizeArea(payload.area),
      payload.marca,
      payload.producto,
      barcode,
      payload.valor_original,
      payload.descuento,
      payload.valor_venta,
      payload.cantidad,
      payload.stock_minimo,
      payload.ubicacion,
      payload.proveedor,
      payload.notas,
      payload.estado,
      normalizeArea(payload.area) === "taller" ? asOptionalId(payload.dispositivo_id) : null,
      normalizeArea(payload.area) === "taller" ? asOptionalId(payload.repuesto_id) : null,
    ]
  );
  return result.rows[0];
}

export async function updateInventoryItem(id, payload) {
  await ensureInventorySchema();
  const result = await query(
    `
      update inventario_items
      set
        marca = $1,
        producto = $2,
        codigo_barra = $3,
        valor_original = $4,
        descuento = $5,
        valor_venta = $6,
        cantidad = $7,
        stock_minimo = $8,
        ubicacion = $9,
        proveedor = $10,
        notas = $11,
        estado = $12,
        dispositivo_id = $13,
        repuesto_id = $14,
        updated_at = now()
      where id = $15
      returning *
    `,
    [
      payload.marca,
      payload.producto,
      payload.codigo_barra,
      payload.valor_original,
      payload.descuento,
      payload.valor_venta,
      payload.cantidad,
      payload.stock_minimo,
      payload.ubicacion,
      payload.proveedor,
      payload.notas,
      payload.estado,
      asOptionalId(payload.dispositivo_id),
      asOptionalId(payload.repuesto_id),
      id,
    ]
  );
  return result.rows[0] || null;
}

export async function disableInventoryItem(id) {
  await ensureInventorySchema();
  return setInventoryItemStatus(id, 0);
}

export async function setInventoryItemStatus(id, estado) {
  await ensureInventorySchema();
  const result = await query(
    "update inventario_items set estado = $1, updated_at = now() where id = $2 returning *",
    [estado ? 1 : 0, id]
  );
  return result.rows[0] || null;
}

export async function moveInventoryStock(id, { tipo, cantidad, motivo, responsable, costo_unitario = 0 }) {
  return transaction(async (client) => {
    const itemResult = await client.query("select * from inventario_items where id = $1 for update", [id]);
    const item = itemResult.rows[0];
    if (!item) return null;

    const previous = Number(item.cantidad || 0);
    const amount = Math.max(0, Math.round(Number(cantidad || 0)));
    const unitCost = Math.max(0, Math.round(Number(costo_unitario || item.valor_original || 0)));
    const totalCost = unitCost * amount;
    let next = previous;

    if (tipo === "entrada") next = previous + amount;
    else if (tipo === "salida") next = Math.max(0, previous - amount);
    else next = amount;

    const updated = await client.query(
      "update inventario_items set cantidad = $1, updated_at = now() where id = $2 returning *",
      [next, id]
    );
    await client.query(
      `
        insert into inventario_movimientos (
          item_id,
          tipo,
          cantidad,
          cantidad_anterior,
          cantidad_nueva,
          costo_unitario,
          total_costo,
          motivo,
          responsable
        )
        values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
      `,
      [id, tipo, amount, previous, next, unitCost, totalCost, motivo || null, responsable || null]
    );

    if (tipo === "entrada" && totalCost > 0) {
      await client.query(
        `
          insert into finanzas_gastos (fecha, categoria, descripcion, monto, tipo, metodo_pago, estado)
          values (current_date, $1, $2, $3, 'compra', null, 1)
        `,
        [item.area === "taller" ? "Compra repuestos" : "Compra productos", motivo || item.producto, totalCost]
      );
    }

    return updated.rows[0];
  });
}
