import { query } from "@/lib/db";
import { rutSearchKey } from "@/lib/rut";

let orderSchemaReady;

async function ensureOrderSchema() {
  if (!orderSchemaReady) {
    orderSchemaReady = query("alter table ordenes add column if not exists reparacion_id integer references repuestos(id)")
      .then(() =>
        query(`
          create table if not exists orden_repuestos (
            id integer generated by default as identity primary key,
            orden_id integer references ordenes(id) on delete cascade,
            inventario_item_id integer references inventario_items(id),
            repuesto_id integer references repuestos(id),
            cantidad integer not null default 1,
            costo_unitario integer default 0,
            precio_unitario integer default 0,
            total_costo integer default 0,
            total_venta integer default 0,
            responsable text,
            created_at timestamptz default now()
          )
        `)
      )
      .then(() => query("alter table orden_repuestos add column if not exists repuesto_id integer references repuestos(id)"))
      .then(() =>
        query("create index if not exists orden_repuestos_inventario_item_idx on orden_repuestos(inventario_item_id)")
      )
      .then(() => query("update estados_ordenes set nombre_estado = 'INGRESADO' where nombre_estado = 'INGRESADA'"))
      .then(() =>
        query(
          "insert into estados_ordenes (id, nombre_estado) values (6, 'ESPERA REPUESTO') on conflict (id) do nothing"
        )
      );
  }
  return orderSchemaReady;
}

export async function getPartUsageHistory(inventarioItemId, { limit = 100 } = {}) {
  await ensureOrderSchema();
  const id = Number(inventarioItemId);
  if (!Number.isInteger(id) || id <= 0) return [];
  const result = await query(
    `
      select
        ore.id,
        ore.orden_id,
        ore.cantidad,
        ore.precio_unitario,
        ore.costo_unitario,
        ore.total_venta,
        ore.responsable,
        ore.created_at,
        o.codigo as orden_codigo,
        o.cliente_id,
        c.nombre as cliente_nombre,
        c.run as cliente_run
      from orden_repuestos ore
      join ordenes o on o.id = ore.orden_id
      left join clientes c on c.id = o.cliente_id
      where ore.inventario_item_id = $1
      order by ore.created_at desc nulls last, ore.id desc
      limit $2
    `,
    [id, Math.min(Math.max(Number(limit) || 100, 1), 300)]
  );
  return result.rows;
}

const ORDER_SELECT = `
  select
    o.id,
    o.created_at,
    o.fecha_entrega,
    o.fecha_salida,
    o.tecnico,
    o.cliente_id,
    o.imei,
    o.metodopago,
    o.codigo,
    o.referencia_externa,
    o.id_equipo,
    o.id_dispositivo,
    o.estado_dispositivo,
    o.reparacion_id,
    o.observacion,
    o.estado,
    o.total_recepcion,
    o.subtotal,
    o.iva,
    o.descuento,
    o.total,
    c.nombre as cliente_nombre,
    c.run as cliente_run,
    c.mail as cliente_mail,
    c.fono as cliente_fono,
    e.nombre as equipo_nombre,
    d.nombre as dispositivo_nombre,
    r.nombre as reparacion_nombre,
    eo.nombre_estado as estado_nombre,
    ee.nombre as estado_dispositivo_nombre
  from ordenes o
  left join clientes c on c.id = o.cliente_id
  left join equipos e on e.id = o.id_equipo
  left join dispositivos d on d.id = o.id_dispositivo
  left join repuestos r on r.id = o.reparacion_id
  left join estados_ordenes eo on eo.id = o.estado
  left join estado_equipos ee on ee.id = o.estado_dispositivo
`;

export async function getOrderStats() {
  await ensureOrderSchema();
  const result = await query(`
    select
      count(*)::int as total,
      count(*) filter (where estado = 1)::int as sin_revisar,
      count(*) filter (where estado = 2)::int as en_revision,
      count(*) filter (where estado = 3)::int as para_retiro,
      count(*) filter (where estado = 6)::int as espera_repuesto
    from ordenes
  `);
  return (
    result.rows[0] || { total: 0, sin_revisar: 0, en_revision: 0, para_retiro: 0, espera_repuesto: 0 }
  );
}

export async function getOrderStates() {
  await ensureOrderSchema();
  const result = await query("select id, nombre_estado from estados_ordenes order by id asc");
  return result.rows;
}

export async function getOrders({ limit = 100, search = "" } = {}) {
  await ensureOrderSchema();
  const cleanSearch = search.trim();
  const params = [];
  let where = "";

  if (cleanSearch) {
    params.push(`%${cleanSearch}%`);
    where = `
      where
        o.id::text ilike $1
        or c.nombre ilike $1
        or c.run ilike $1
        or d.nombre ilike $1
        or e.nombre ilike $1
        or r.nombre ilike $1
        or o.codigo ilike $1
    `;
  }

  params.push(limit);
  const result = await query(
    `
      ${ORDER_SELECT}
      ${where}
      order by coalesce(o.created_at, o.fecha_entrega, now()) desc, o.id desc
      limit $${params.length}
    `,
    params
  );

  return result.rows;
}

export async function getReviewOrders({ id = "", run = "", nombre = "", limit = 100 } = {}) {
  await ensureOrderSchema();
  const cleanId = String(id || "").trim();
  const cleanRun = String(run || "").trim();
  const cleanName = String(nombre || "").trim();
  const params = [];
  let where = "";

  if (cleanId) {
    const numberId = Number(cleanId);
    if (!Number.isInteger(numberId) || numberId < 1) return [];
    params.push(numberId);
    where = "where o.id = $1";
  } else if (cleanRun) {
    params.push(rutSearchKey(cleanRun));
    where = "where lower(regexp_replace(coalesce(c.run, ''), '[^0-9kK]', '', 'g')) = $1";
  } else if (cleanName) {
    params.push(`%${cleanName}%`);
    where = "where c.nombre ilike $1";
  } else {
    return [];
  }

  params.push(limit);
  const result = await query(
    `
      ${ORDER_SELECT}
      ${where}
      order by coalesce(o.created_at, o.fecha_entrega, now()) desc, o.id desc
      limit $${params.length}
    `,
    params
  );

  return result.rows;
}

export async function getOrder(id) {
  await ensureOrderSchema();
  const orderResult = await query(`${ORDER_SELECT} where o.id = $1 limit 1`, [id]);
  const order = orderResult.rows[0];
  if (!order) return null;

  const [responses, revisions, services, parts] = await Promise.all([
    query(
      `
        select r.id, r.respuesta, r.check_resp, p.descripcion as pregunta
        from respuestas r
        left join preguntas p on p.id = r.pregunta_id
        where r.orden_id = $1
        order by r.id asc
      `,
      [id]
    ),
    query(
      `
        select r.id, r.responsable, r.observacion, r.created_at, eo.nombre_estado
        from revisiones r
        left join estados_ordenes eo on eo.id = r.id_estado
        where r.orden_id = $1
        order by r.created_at desc nulls last, r.id desc
      `,
      [id]
    ),
    query(
      `
        select ohs.id, ohs.servicio_id, ohs.responsable, ohs.created_at, s.nombre, s.precio
        from orden_has_servicios ohs
        left join servicios s on s.id = ohs.servicio_id
        where ohs.orden_id = $1
        order by ohs.created_at desc nulls last, ohs.id desc
      `,
      [id]
    ),
    query(
      `
        select
          ore.id,
          ore.inventario_item_id,
          ore.repuesto_id,
          ore.cantidad,
          ore.costo_unitario,
          ore.precio_unitario,
          ore.total_costo,
          ore.total_venta,
          coalesce(ii.producto, r.nombre) as producto,
          ii.marca,
          ii.codigo_barra
        from orden_repuestos ore
        left join inventario_items ii on ii.id = ore.inventario_item_id
        left join repuestos r on r.id = coalesce(ore.repuesto_id, ii.repuesto_id)
        where ore.orden_id = $1
        order by ore.id asc
      `,
      [id]
    ),
  ]);

  return {
    ...order,
    responses: responses.rows,
    revisions: revisions.rows,
    services: services.rows,
    repuestos: parts.rows,
  };
}
