export const BRAND_MODELS = {
  Apple: [
    "iPhone 2G",
    "iPhone 3G",
    "iPhone 3GS",
    "iPhone 4",
    "iPhone 4s",
    "iPhone 5",
    "iPhone 5c",
    "iPhone 5s",
    "iPhone 6",
    "iPhone 6 Plus",
    "iPhone 6s",
    "iPhone 6s Plus",
    "iPhone SE (1st gen)",
    "iPhone 7",
    "iPhone 7 Plus",
    "iPhone 8",
    "iPhone 8 Plus",
    "iPhone X",
    "iPhone XR",
    "iPhone XS",
    "iPhone XS Max",
    "iPhone 11",
    "iPhone 11 Pro",
    "iPhone 11 Pro Max",
    "iPhone SE (2nd gen)",
    "iPhone 12 mini",
    "iPhone 12",
    "iPhone 12 Pro",
    "iPhone 12 Pro Max",
    "iPhone 13 mini",
    "iPhone 13",
    "iPhone 13 Pro",
    "iPhone 13 Pro Max",
    "iPhone SE (3rd gen)",
    "iPhone 14",
    "iPhone 14 Plus",
    "iPhone 14 Pro",
    "iPhone 14 Pro Max",
    "iPhone 15",
    "iPhone 15 Plus",
    "iPhone 15 Pro",
    "iPhone 15 Pro Max",
    "iPhone 16e",
    "iPhone 16",
    "iPhone 16 Plus",
    "iPhone 16 Pro",
    "iPhone 16 Pro Max",
    "iPhone 17e",
    "iPhone 17",
    "iPhone Air",
    "iPhone 17 Pro",
    "iPhone 17 Pro Max",
  ],
  Samsung: [
    "Galaxy S22",
    "Galaxy S22+",
    "Galaxy S22 Ultra",
    "Galaxy S23 FE",
    "Galaxy S23",
    "Galaxy S23+",
    "Galaxy S23 Ultra",
    "Galaxy S24 FE",
    "Galaxy S24",
    "Galaxy S24+",
    "Galaxy S24 Ultra",
    "Galaxy S25 FE",
    "Galaxy S25",
    "Galaxy S25+",
    "Galaxy S25 Edge",
    "Galaxy S25 Ultra",
    "Galaxy S26",
    "Galaxy S26+",
    "Galaxy S26 Ultra",
    "Galaxy Z Flip4",
    "Galaxy Z Fold4",
    "Galaxy Z Flip5",
    "Galaxy Z Fold5",
    "Galaxy Z Flip6",
    "Galaxy Z Fold6",
    "Galaxy Z Flip7",
    "Galaxy Z Fold7",
    "Galaxy A14",
    "Galaxy A14 5G",
    "Galaxy A15",
    "Galaxy A15 5G",
    "Galaxy A16",
    "Galaxy A16 5G",
    "Galaxy A24",
    "Galaxy A25 5G",
    "Galaxy A26 5G",
    "Galaxy A34 5G",
    "Galaxy A35 5G",
    "Galaxy A36 5G",
    "Galaxy A54 5G",
    "Galaxy A55 5G",
    "Galaxy A56 5G",
  ],
  Huawei: [
    "P60",
    "P60 Pro",
    "P60 Art",
    "Pura 70",
    "Pura 70 Pro",
    "Pura 70 Pro+",
    "Pura 70 Ultra",
    "Pura 80",
    "Pura 80 Pro",
    "Pura 80 Pro+",
    "Pura 80 Ultra",
    "Mate 50",
    "Mate 50 Pro",
    "Mate 60",
    "Mate 60 Pro",
    "Mate 60 Pro+",
    "Mate 70",
    "Mate 70 Pro",
    "Mate 70 Pro+",
    "Mate X3",
    "Mate X5",
    "Mate X6",
    "Mate XT",
    "Nova 11",
    "Nova 11 Pro",
    "Nova 12",
    "Nova 12 Pro",
    "Nova 13",
    "Nova 13 Pro",
    "Nova 14",
    "Nova 14 Pro",
  ],
};

export const PART_TYPES = [
  "Pantalla",
  "Bateria",
  "Flex",
  "Camara",
  "Auricular",
  "Altavoz",
  "Tapa trasera",
  "Vidrio camara",
  "Modulo Face ID",
];
